### ISSUE TITLE
Field jurusan pada program studi tidak ditemukan

### ISSUE THREAD

**Issue by ilomon10** [Pi-Laboratory/akademik-backend#1]
Field jurusan di endpoint program studi tidak ditemukan.

**Masukan**: Mungkin bisa juga tambah opsi query untuk ambil sekalian dengan relasi terkait dengan model.

Contoh ada relasi jurusan dengan program studi, tinggal pake query begini untuk ambil informasi sekaligus
```js
app["study-programs"].find({
  query: {
    $include: [{
      model: "major",
      $select: ["id", "name"],
      as: "major"
    }]
  }
})
```

**Comment by EdgarJeremy** [comment]
Fixed in 7cf22bc
